### ISSUE TITLE
https://astroneermods.space/ is offline

### ISSUE THREAD

**Issue by pat600130** [AstroTechies/astro_modloader#24]
the reason i bring this up is because the modloader is still checking https://astroneermods.space/ when it probably should be checking https://astromod.space/

**Comment by Corporalwill123** [comment]
The site to check is determined by the metadata of the mod, so not a modloader issue. 

Also that site is a copy made without permission from the original owner, and does not have the files needed to make that work in the first place.

**Comment by pat600130** [comment]
ah ok

**Comment by Famous5000** [comment]
@konsti219 Maybe instead of deleting every issue which mentions it, maybe put up a sticky which indicates that the site is in direct violation? Since I'm not the only one who's pointed this out, and evidently others aren't looking at the closed issues? I get not wanting attention drawn to it but you have to strike a middle ground:

If you keep removing it from the GitHub, people are just going to keep pointing it out (and making you angrier due to people being "stupid")
But if you have a pinned issue which indicates that the site isn't good then it'll cause more people to stop asking about it.

*and besides how are people going to have access to the discord to have access to all of the archived mods if you aren't going to let them see the invite by removing the only other area where it exists publicly?*

The point I'm trying to get across is stop trying to use "Security by obfuscation" and instead make sure people know it's not right, and link them to a place where you *can* at least get the stuff (the discord)
